# Generated by Django 5.2.17 on 2026-08-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsprediction',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsprediction',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newsprediction',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
