# Generated by Django 5.2.17 on 2026-09-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_newsprediction_published_at_newsprediction_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsprediction',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
